config/routes.rb
Bugmetilidoit::Application.routes.draw do
  devise_scope :user do
    namespace :api do
      namespace :v1 do
        resources :sessions, :only => [:create, :destroy]
        resources :registrations, :only => [:create]
      end
    end
  end
  
  resources :assigned_networks
  
  resources :networks
  
  #match 'assigned_tasks/:id/mark_completed' => 'assigned_tasks#update', as: :complete_assigned_task, via: :get
  
  resources :reminders

  resources :tasks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do
    resources :assigned_tasks
    member do
      get 'oauth'
      get 'twitter_oauth'
    end
  end
end

app/models/network.rb
class Network < ActiveRecord::Base
  has_many :assigned_networks, dependent: :destroy
  has_many :assigned_tasks, through: :assigned_networks
  
  attr_accessible :name
end

app/controllers/networks_controller.rb
class NetworksController < InheritedResources::Base
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/views/networks/_form.html.erb
<%= simple_form_for(@network) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/networks/edit.html.erb
<h1>Editing network</h1>

<%= render 'form' %>

<%= link_to 'Show', @network %> |
<%= link_to 'Back', networks_path %>

app/views/networks/index.html.erb
<h1>Listing networks</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @networks.each do |network| %>
  <tr>
    <td><%= network.name %></td>
    <td><%= link_to 'Show', network %></td>
    <td><%= link_to 'Edit', edit_network_path(network) %></td>
    <td><%= link_to 'Destroy', network, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Network', new_network_path %>

app/views/networks/new.html.erb
<h1>New network</h1>

<%= render 'form' %>

<%= link_to 'Back', networks_path %>

app/views/networks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @network.name %>
</p>


<%= link_to 'Edit', edit_network_path(@network) %> |
<%= link_to 'Back', networks_path %>