config/routes.rb
Bugmetilidoit::Application.routes.draw do
  devise_scope :user do
    namespace :api do
      namespace :v1 do
        resources :sessions, :only => [:create, :destroy]
        resources :registrations, :only => [:create]
      end
    end
  end
  
  resources :assigned_networks
  
  resources :networks
  
  #match 'assigned_tasks/:id/mark_completed' => 'assigned_tasks#update', as: :complete_assigned_task, via: :get
  
  resources :reminders

  resources :tasks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do
    resources :assigned_tasks
    member do
      get 'oauth'
      get 'twitter_oauth'
    end
  end
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  belongs_to :assigned_task
  has_one :user, through: :assigned_task
  has_one :task, through: :assigned_task
  has_many :networks, through: :assigned_task
  
  attr_accessible :sent_at
  
  after_create :send_notices
  
  def send_notices
    if false
      Bitly.use_api_version_3
      bitly = Bitly.new("gunnertech", "R_b75c09fa28aa15f9e53ccb9245a9acf6")
      if assigned_task.task_url.present?
        full_url = assigned_task.task_url
      else
        full_url = Rails.application.routes.url_helpers.user_assigned_task_url(user, assigned_task, host: ENV['HOST'])
      end
    
      begin
        u = bitly.shorten(full_url)
      rescue
        Rails.logger.warn("^^^^BAD URL: #{full_url}")
        return true
      end
    
      body = "#{task.title}"[0..159]
    
      ReminderMailer.reminder_email(self,user).deliver if networks.include?(Network.find_or_create_by_name('Email'))
    
      if networks.include?(Network.find_or_create_by_name('SMS'))
        client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
        to = Rails.env.production? ? "+1#{user.mobile}" : "+1#{ENV['DUMMY_NUMBER']}"
        number = ENV['TWILIO_NUMBERS'].split(",").sample
        begin
          client.account.sms.messages.create(
            :from => "+1#{number}",
            :to => to,
            :body => "#{body} Did it? Click here: #{full_url} - Not you? reply 'STOP'"
          )
        rescue
          Rails.logger.warn("^^^^BAD COMBO: from: #{number} to: #{to}")
        end
      end
    
      if networks.include?(Network.find_or_create_by_name('Twitter'))
        body = "@#{user.twitter_user_name} #{body} #{full_url}"[0..139]
        Twitter.update(body) unless user.twitter_user_name.blank?
      end
    
      if networks.include?(Network.find_or_create_by_name('Facebook'))
        if assigned_task.user.facebook_access_token.present?
          assigned_task.post_to_facebook("I haven't #{task.to_s} yet so Bug Me Til I Do It is spamming me. #{full_url}") rescue nil
        end
      end
    end
    
    self.assigned_task.remind_at = assigned_task.remind_at + assigned_task.reminder_frequency.to_i.minutes
    self.assigned_task.save!
  end
  
end

app/controllers/reminders_controller.rb
class RemindersController < InheritedResources::Base
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_form.html.erb
<%= simple_form_for @reminder, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :assigned_task_id %>
  <%= f.input :sent_at %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reminders_path, :class => 'btn' %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<%- model_class = Reminder -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reminders/index.html.erb
<%- model_class = Reminder -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:assigned_task_id) %></th>
      <th><%= model_class.human_attribute_name(:sent_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= link_to reminder.id, reminder_path(reminder) %></td>
        <td><%= reminder.assigned_task_id %></td>
        <td><%= reminder.sent_at %></td>
        <td><%=l reminder.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reminder_path(reminder), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reminder_path(reminder),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reminder_path,
            :class => 'btn btn-primary' %>

app/views/reminders/new.html.erb
<%- model_class = Reminder -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reminders/show.html.erb
<%- model_class = Reminder -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:assigned_task_id) %>:</strong></dt>
  <dd><%= @reminder.assigned_task_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sent_at) %>:</strong></dt>
  <dd><%= @reminder.sent_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reminders_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reminder_path(@reminder), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reminder_path(@reminder),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>