config/routes.rb
Bugmetilidoit::Application.routes.draw do
  devise_scope :user do
    namespace :api do
      namespace :v1 do
        resources :sessions, :only => [:create, :destroy]
        resources :registrations, :only => [:create]
      end
    end
  end
  
  resources :assigned_networks
  
  resources :networks
  
  #match 'assigned_tasks/:id/mark_completed' => 'assigned_tasks#update', as: :complete_assigned_task, via: :get
  
  resources :reminders

  resources :tasks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do
    resources :assigned_tasks
    member do
      get 'oauth'
      get 'twitter_oauth'
    end
  end
end

app/models/assigned_network.rb
class AssignedNetwork < ActiveRecord::Base
  belongs_to :network
  belongs_to :assigned_task
  
  attr_accessible :network_id, :network
end

app/controllers/assigned_networks_controller.rb
class AssignedNetworksController < InheritedResources::Base
end

app/helpers/assigned_networks_helper.rb
module AssignedNetworksHelper
end

app/views/assigned_networks/_form.html.erb
<%= simple_form_for(@assigned_network) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :network %>
    <%= f.association :assigned_task %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/assigned_networks/edit.html.erb
<h1>Editing assigned_network</h1>

<%= render 'form' %>

<%= link_to 'Show', @assigned_network %> |
<%= link_to 'Back', assigned_networks_path %>

app/views/assigned_networks/index.html.erb
<h1>Listing assigned_networks</h1>

<table>
  <tr>
    <th>Network</th>
    <th>Assigned task</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assigned_networks.each do |assigned_network| %>
  <tr>
    <td><%= assigned_network.network %></td>
    <td><%= assigned_network.assigned_task %></td>
    <td><%= link_to 'Show', assigned_network %></td>
    <td><%= link_to 'Edit', edit_assigned_network_path(assigned_network) %></td>
    <td><%= link_to 'Destroy', assigned_network, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assigned network', new_assigned_network_path %>

app/views/assigned_networks/new.html.erb
<h1>New assigned_network</h1>

<%= render 'form' %>

<%= link_to 'Back', assigned_networks_path %>

app/views/assigned_networks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Network:</b>
  <%= @assigned_network.network %>
</p>

<p>
  <b>Assigned task:</b>
  <%= @assigned_network.assigned_task %>
</p>


<%= link_to 'Edit', edit_assigned_network_path(@assigned_network) %> |
<%= link_to 'Back', assigned_networks_path %>