config/routes.rb
Bugmetilidoit::Application.routes.draw do
  devise_scope :user do
    namespace :api do
      namespace :v1 do
        resources :sessions, :only => [:create, :destroy]
        resources :registrations, :only => [:create]
      end
    end
  end
  
  resources :assigned_networks
  
  resources :networks
  
  #match 'assigned_tasks/:id/mark_completed' => 'assigned_tasks#update', as: :complete_assigned_task, via: :get
  
  resources :reminders

  resources :tasks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do
    resources :assigned_tasks
    member do
      get 'oauth'
      get 'twitter_oauth'
    end
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Bug Me Til I Do It", root_path, :class => 'brand' %>

<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<div class="nav-collapse collapse">
  <ul class="nav">
    <% if user_signed_in? %>
      <li>
      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
      </li>
    <% else %>
      <li>
      <%= link_to 'Login', new_user_session_path %>
      </li>
    <% end %>
    <% if user_signed_in? %>
      <li>
      <%= link_to 'Edit account', edit_user_registration_path %>
      </li>
      <% if current_user.has_role? :admin %>
        <li>
        <%= link_to 'Admin', users_path %>
        </li>
      <% end %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle"data-toggle="dropdown">
          <%= t('my_tasks') %>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <% if can? :create, AssignedTask %>
            <li><%= link_to t('create_new'), new_user_assigned_task_path(current_user)  %></li>
          <% end %>
          <li><%= link_to t('active'), user_assigned_tasks_path(current_user,    view: 'active')  %></li>
          <li><%= link_to t('completed'), user_assigned_tasks_path(current_user, view: 'completed')  %></li>
          <li><%= link_to t('abandoned'), user_assigned_tasks_path(current_user, view: 'abandoned')  %></li>
        </ul>
      </li>
      <li><%= link_to t('tasks'), tasks_path %></li>
    <% else %>
      <li>
      <%= link_to 'Sign up', new_user_registration_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bug Me Til I Do It" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bug Me Til I Do IT" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <link rel="shortcut icon" href="/favicon.ico" />
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-23471613-26', 'bugmetilidoit.com');
      ga('send', 'pageview');

    </script>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
          <% if content_for?(:breadcrumb) %>
            <div id="breadcrumbs" class="row-fluid">
              <%= content_for(:breadcrumb) %>
            </div>
          <% end %>
           <div class="row-fluid">
            <div class="span12">
              <div class="scroll-pane">
                <%= render 'layouts/messages' %>
                <%= yield %>
              </div>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <footer class="main">
      <div class="container">
        <p>Designed and developed by <a href="http://gunnertech.com">Gunner Technology</a>.</p>
        <p>
          <%= link_to "Feedback", "" %> |
          <%= link_to "Privacy Policy", "" %> |
          <%= link_to "Terms of Service", "" %> |
          <%= link_to "License our Content", "" %> |
          <%= link_to "Media Kit", "" %> |
          <%= link_to "About Us", "" %>
        </p>
        
        <p><%= t(:copyright) %> &#169; Gunner Technology <%= t(:all_rights_reserved)%>.</p>
      </div>
    </footer>
  </body>
</html>